---
- name: deploy cloud hosts
  rax:
    exact_count=yes
    count=1
    creds_file="{{rax_creds_file}}"
    name="{{item}}"
    group="{{item}}"
    auto_increment=no
    image="{{hostvars[item]['image']}}"
    flavor="{{hostvars[item]['flavor']}}"
    region="{{hostvars[item]['region']}}"
    networks="public","private","{{hostvars[item]['region']}}_management"
    config_drive=yes
    user_data="{{hostvars[item]['cloud_init_file']}}"
    state=present
    wait=yes
    wait_timeout=300
  with_items: "{{groups[create_group]}}"
  register: rax

- name: debug rax
  debug: var="{{rax['results'][0].instances|to_nice_json}}"

- name: debug hostvars
  debug: var="{{item}}"
  with_dict: "{{hostvars['eos.randomuser.org']}}"

- name: make an A record for the new instance
  rax_dns_record:
    creds_file="{{rax_creds_file}}"
    data="{{item.accessIPv4}}"
    domain="{{'.'.join(item['name'].split('.')[1:])}}"
    name="{{item.name}}"
    region=DFW
    state=present
    type=A
  with_items: "{{rax['results'][0].instances}}"

- name: make an AAAA record for the new instance
  rax_dns_record:
    creds_file="{{rax_creds_file}}"
    data="{{item.rax_accessipv6}}"
    domain="{{'.'.join(item['name'].split('.')[1:])}}"
    name="{{item.name}}"
    region=DFW
    state=present
    type=AAAA
  with_items: "{{rax['results'][0].instances}}"

