- name: set up interfaces
  include: interface_setup.yml

- name: docker CE host prep
  include: "docker_{{ docker_vendor.name }}.yml"

- name: template an rke cluster.yml
  delegate_to: localhost
  run_once: true
  template:
    src: cluster.yml
    dest: rke/cluster.yml

