apiVersion: v1
kind: Service
metadata:
  name: poddington
  labels:
    app: poddington
spec:
  selector:
    app: poddington
  ports: 
    - protocol: TCP
      port: 8950
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Pod
metadata: 
  name: poddington
  labels:
    app: poddington
spec:
  containers:
    - name: poddington-http
      image: nginx
      ports:
        - protocol: TCP
          containerPort: 80
          name: http-inside
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  generation: 2
  name: poddington-ingress
  namespace: default
spec:
  rules:
  - host: poddington1.randomuser.org
    http:
      paths:
      - backend:
          serviceName: poddington
          servicePort: 8950
  - host: poddington2.randomuser.org
    http:
      paths:
      - backend:
          serviceName: poddington
          servicePort: 8950
