apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poddington-pool
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

---
apiVersion: v1
kind: Service
metadata:
  name: poddington
  labels:
    app: poddington
spec:
  selector:
    app: poddington
  ports: 
    - protocol: TCP
      port: 8950
      targetPort: 9103
      name: http
    - protocol: TCP
      port: 8960
      targetPort: 9090
      name: prometheus
    - protocol: UDP
      port: 25825
      targetPort: 25826
      name: collectd
---
apiVersion: v1
kind: Pod
metadata: 
  name: poddington
  labels:
    app: poddington
spec:
  volumes:
    - name: poddington-vol
      persistentVolumeClaim:
        claimName: poddington-pool
  initContainers:
    - name: content
      image: fedora
      command:
        - /usr/bin/touch
        - /usr/local/apache2/htdocs/index.html
      volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs/"
          name: poddington-vol
  containers:
    - name: poddington-prometheus
      image: prom/prometheus
      volumeMounts:
        - mountPath: "/prometheus-data"
          name: poddington-vol
      ports:
        - protocol: TCP
          containerPort: 9090
          name: prometheus
    - name: poddington-collectd
      image: prom/collectd-exporter
      ports:
        - protocol: TCP
          containerPort: 9103
          name: write-http
        - protocol: UDP
          containerPort: 25826
      args: ['collectd.listen_address=":25826"']
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  generation: 2
  name: poddington-ingress
  namespace: default
spec:
  rules:
  - host: poddington1.randomuser.org
    http:
      paths:
      - backend:
          serviceName: poddington
          servicePort: 8950
  - host: poddington2.randomuser.org
    http:
      paths:
      - backend:
          serviceName: poddington
          servicePort: 8960
