- name: get instance uuid
  shell: cat /var/lib/cloud/data/instance-id
  register: uuid
- name: make an MX record
  delegate_to: localhost
  rax_dns_record:
    creds_file="{{rax_creds_file}}"
    data="{{ansible_fqdn}}"
    priority=10
    domain="{{'.'.join(ansible_fqdn.split('.')[1:])}}"
    name="{{'.'.join(ansible_fqdn.split('.')[1:])}}"
    region=DFW
    state=present
    type=MX
- name: claim a PTR record
  delegate_to: localhost
  rax_dns_record:
    creds_file="{{rax_creds_file}}"
    name="{{ansible_fqdn}}"
    type=PTR
    data="{{ansible_default_ipv4.address}}"
    server="{{uuid.stdout}}"
    region=DFW
    state=present

- name: create SPF record
  delegate_to: localhost
  rax_dns_record:
    creds_file="{{rax_creds_file}}"
    data="v=spf1 mx mx:{{domain}} -all"
    domain="{{'.'.join(ansible_fqdn.split('.')[1:])}}"
    region=DFW
    state=present
    type=MX


#rdns: domain="{{.'.join(ansible_default_ipv4.address.split('.')[::-1]) + '.in-addr.arpa'}}"
