- name: build rax cloud hosts
  hosts: rax_cloud_hosts
  vars:
    domain: "{{ lookup('pipe', 'hostname -d') }}"
  #  vars_files: 
  #  - ~/ansible.randomuser.org/ansible/defaults/main.yml
  tags:
    - build
    - cloud_build
  roles:
    - rax_cloud_build

- name: set up interfaces
  hosts:
    - gateway
  vars:
    domain: "{{ lookup('pipe', 'hostname -d') }}"
  become: true
  tags:
    - static_address
  roles:
    - static_address

- name: deploy dhcpd container
  hosts:
    - gateway
  tags:
    - dhcpd
  become: True
  vars:
    domain: "{{ lookup('pipe', 'hostname -d') }}"
  roles:
    - dhcpd_peer
