---
- include: cloud_spinup.yml
- name: do gateway stuff
  hosts: gateway.randomuser.org
  vars_files:
    - ~/ansible.randomuser.org/ansible/vars/global.yml
  tasks:
    - include: "{{tasks}}/rax/create_rackspace_dns_record.yml"
- name: create a controller impersonator
  hosts: proteus.randomuser.org
  vars_files: 
    - ~/ansible.randomuser.org/ansible/vars/global.yml
  roles: 
    - controller_impersonator

- name: deploy a mailserver
  hosts: proteus.randomuser.org
  vars_files: 
    - ~/ansible.randomuser.org/ansible/vars/global.yml
    - ~/ansible.randomuser.org/ansible/vars/mailserver.yml
  tasks:
    - name: install git for certbot
      dnf: name=git state=present
    - name: open firewall for certbot
      firewalld: service=https timeout=300 state=enabled permanent=no
  roles: 
    - ansible-certbot
    - mailserver
      #    - imapd

