- name: build rax cloud hosts
  hosts: rax_cloud_hosts
  vars:
    domain: "{{ lookup('pipe', 'hostname -d') }}"
  #  vars_files: 
  #  - ~/ansible.randomuser.org/ansible/defaults/main.yml
  tags:
    - build
    - cloud_build
  roles:
    - rax_cloud_build

- name: build local virt host
  hosts: kvm_hosts
  tags:
    - kvm_hosts
  roles:
    - kvm_host

