---
- name: deploy cloud hosts
  hosts: localhost
  gather_facts: False
  connection: local 
  vars_files: 
    - ~/ansible.randomuser.org/ansible/vars/global.yml
    - ~/ansible.randomuser.org/ansible/vars/cloud_networks.yml 
  vars:
    - create_group: cloud_hosts
    - domains:
      - randomuser.org
    - exnet: public
    - servicenet: private
  handlers:
    - include: "{{ tasks }}/rax/deploy_shim.yml"
  tasks:
    - include: "{{ tasks }}/rax/create_rackspace_domain.yml"
    - include: "{{ tasks }}/rax/create_rackspace_networks.yml"
    - include: "{{ tasks }}/rax/create_rackspace_instance.yml" 

#- name: make ipsec endpont
#  hosts: 
#    - proteus.randomuser.org
#    - gateway.randomuser.org
#  become: True
#  become_method: sudo
#  gather_facts: True
#  vars_files: 
#    - ~/ansible.randomuser.org/ansible/vars/global.yml
#    - ~/ansible.randomuser.org/ansible/vars/cloud_networks.yml 
#  vars:
#    - placeholder: True
#  roles:
#    - ipsec_endpoint
- name: do gateway stuff
  hosts: gateway.randomuser.org
  vars_files:
    - ~/ansible.randomuser.org/ansible/vars/global.yml
  tasks:
    - include: "{{tasks}}/rax/create_rackspace_dns_record.yml"
- name: create a controller impersonator
  hosts: proteus.randomuser.org
  vars_files: 
    - ~/ansible.randomuser.org/ansible/vars/global.yml
  roles: 
    - controller_impersonator

- name: deploy a mailserver
  hosts: proteus.randomuser.org
  vars_files: 
    - ~/ansible.randomuser.org/ansible/vars/global.yml
    - ~/ansible.randomuser.org/ansible/vars/mailserver.yml
  vars:
    rax_uuid: "{{lookup('pipe', 'cat /var/lib/cloud/data/instance-id'}}"
  tasks:
    - name: install git for certbot
      dnf: name=git state=present
    - name: open firewall for certbot
      firewalld: service=https timeout=300 state=enabled permanent=no
  roles: 
    - ansible-certbot
    - mailserver
      #    - imapd

