- name: default stub
  hosts: kube
  gather_facts: False
  become: True
  tags:
    - default
  roles:
    - default
- name: virt stub
  hosts: kube
  tags: 
    - virt
  become: True
  roles:
    - virt_host
- name: fact stub
  hosts: kube
  tags:
    - store_key
  tasks:
    - include: tasks/store_key.yml
    - debug: var=ansible_local.vars_file.taxonomy.bullshit
