- name: default stub
  hosts: all
  gather_facts: False
  become: True
  tags:
    - default
  roles:
    - default
- name: virt stub
  hosts: kube
  tags: 
    - virt
  become: True
  roles:
    - virt_host
- name: impersonator stub
  hosts: kube
  become: True
  tags:
    - impersonator
  roles:
    - controller_impersonator
- name: fact stub
  hosts: kube
  tags:
    - store_key
  tasks:
    - include: tasks/store_key.yml
    - debug: var=ansible_local.vars_file.taxonomy.bullshit
- name: foreman stub
  hosts: foreman_proxy
  tags:
    - foreman_proxy
  roles:
    - foreman_proxy
- name: replica stub
  hosts: replicas
  tags:
    - replica
  roles:
    - controller_base
    - replica
