- name: create spool directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: foreman-proxy
    group: foreman-proxy
    mode: 0755
  with_items: 
    - "{{ store_info.path }}"
    - "{{ store_info.path }}/local_aggregation"
- name: link aggregation dir to system roles path
  become: true
  file:
    dest: /etc/ansible/roles
    src: "{{ store_info.path }}/local_aggregation"
    owner: foreman-proxy
    group: foreman-proxy
    force: yes
    state: link
- name: pull source repos
  become: true
  become_user: foreman-proxy
  git:
    clone: yes
    dest: "{{ store_info.path }}/{{ item.uri | urlsplit('path') | basename | regex_replace('.git$', '') }}"
    recursive: yes
    repo: "{{ item.uri }}"
  with_items: "{{ source_repos }}"
- name: template out aggregation script
  become: true
  copy:
    mode: 0755
    dest: /usr/share/foreman-proxy/bin/update_ansible_roles.sh
    content: |
      #!/usr/bin/bash
      # symlinks role paths from {{ store_info.path }} subdirectories
      # into {{ store_info.path }}/local_aggregation
      pushd {{ store_info.path }}
      {% for repo in source_repos %}
      SHORT_PATH={{ repo.uri | urlsplit('path') | basename | regex_replace('.git$', '') }}
      if [[ -d $SHORT_PATH ]]; then
        pushd $SHORT_PATH
        git pull
        popd
      else
        git clone {{ repo.uri }}
      fi
      find {{ store_info.path }}/SHORT_PATH/{{ repo.roles_path }} \
      -maxdepth 1 -mindepth 1 -type d | \
        while read path; do 
          [ -L {{ store_info.path }}/local_aggregation/$(basename $path) ] || ln -sf $path {{ store_info.path }}/local_aggregation/;done
      {% endfor %}
- name: create repo sync service
  become: true
  copy:
    dest: /etc/systemd/system/ansible-repo-sync.service
    content: |
      [Unit]
      Description=Syncs ansible repository content to {{ store_info.path }}
      [Service]
      Type=oneshot
      ExecStart=/usr/share/foreman-proxy/bin/update_ansible_roles.sh
      User=foreman-proxy
- name: create repo sync timer job
  become: true
  copy: 
    dest: /etc/systemd/system/ansible-repo-sync.timer
    content: | 
      [Unit]
      Description=Syncs ansible repository content to {{ store_info.path }}
      [Timer]
      OnBootSec=5min
      OnUnitActiveSec={{ store_info.sync_frequency }}
      [Install]
      WantedBy=timers.target
- name: enable the timer
  systemd:
    daemon_reload: yes
    name: ansible-repo-sync.timer
    enabled: yes

