homelab:
  hosts:
    gateway:
    silo:
  vars: 
    snmp_relay: trap0.randomuser.org
  children:
    kube0:
      hosts:
        k8s-alpha.randomuser.org:
        k8s-epsilon.randomuser.org:
        k8s-delta.randomuser.org:
        k8s-silo.randomuser.org:
    syslog_proxy:
      hosts:
        logproxy0.randomuser.org:
    storage:
      children:
        hosts:
          silo:
    compute:
      children:
        fast:
          hosts:
            epsilon:
        slow:
          hosts:
            alpha:
        median:
          hosts:
            delta:
