- name: install katello repo release rpm
  yum:
    name: "https://fedorapeople.org/groups/katello/releases/yum/{{ katello_release_branch }}/katello/el7/x86_64/katello-repos-latest.rpm"
    state: latest
  register: katello_release_rpm
- include: katello_release_change.yml
  when: katello_release_rpm.changed

- name: install foreman release rpm
  yum:
    name: "https://yum.theforeman.org/releases/{{ foreman_release_branch }}/el7/x86_64/foreman-release.rpm"
    state: latest
  register: foreman_release_rpm
- include: foreman_release_change.yml
  when: foreman_release_rpm.changed
- name: install less version-dependent release rpms
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - foreman-release-scl
    - https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
- name: puppet confusion safety valve
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: exclude
    value: puppet*
- name: install the katello
  yum: 
    name: katello
    state: present
- name: prep hostfile
  tags:
    - regexp
  lineinfile:
    regexp: ^(127.0.0.1).*
    backrefs: yes
    line: |
      \1   {{ ansible_nodename }} {{ ansible_hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4
    state: present
    path: /etc/hosts
  
- name: invoke foreman_installer
  tags:
    - foreman_installer
  copy:
    content: |
      foreman-installer --scenario katello \
        --verbose \
        --enable-certs \
        --enable-foreman \
        --enable-foreman-cli \
        --enable-foreman-cli-ansible \
        --enable-foreman-cli-remote-execution \
        --enable-foreman-compute-ec2 \
        --enable-foreman-compute-libvirt \
        --enable-foreman-compute-rackspace \
        --enable-foreman-compute-vmware \
        --enable-foreman-plugin-ansible \
        --enable-foreman-plugin-remote-execution \
        --enable-foreman-plugin-setup \
        --enable-foreman-plugin-tasks \
        --enable-foreman-plugin-templates \
        --foreman-proxy-ssl-port 8843
    dest: /tmp/installer.sh
