- name: install virt packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - "@^virtualization-host-environment"
- name: start libvirtd
  service:
    name: libvirtd
    state: started
    enabled: True
     

