- name: copy the seed image for use
  copy:
    remote_src: yes
    src: /var/lib/libvirt/images/rhel7-latest.qcow2
    dest: "{{ seed_image }}"
    force: no
- name: template the cloud_config data
  template:
    src: user_data.j2
    dest: "/tmp/user_data_{{ provision_hostname }}.cfg"
- name: apply cloud_config to the image
  shell: "virt-copy-in -a  {{ seed_image }} /tmp/user_data_{{ provision_hostname }}.cfg /etc/cloud/cloud.cfg.d/"
