foreman:
  install:
    options:
      - "--detailed-exitcodes"
      - "--no-colors"
      - "--log-level {{ loglevel|default('debug') }}"
      - "--verbose"
      - "--verbose-log-level {{ loglevel|default('debug') }}"
      - "--enable-foreman-plugin-ansible"
      - "--enable-foreman-plugin-cockpit"
      - "--enable-foreman-plugin-dhcp-browser"
      - "--enable-foreman-plugin-discovery"
      - "--enable-foreman-plugin-docker"
      - "--enable-foreman-plugin-hooks"
      - "--enable-foreman-compute-ec2"
      - "--enable-foreman-compute-gce"
      - "--enable-foreman-compute-libvirt"
      - "--enable-foreman-compute-rackspace"
      - "--enable-foreman-proxy-plugin-pulp"
      - "--enable-foreman-proxy-plugin-remote-execution-ssh"
      - "--foreman-admin-email {{ foreman_admin_contact|default('foreman_admins') }}@{{ domain }}"
      - "--foreman-admin-password {{ foreman.admin.password|default(lookup('password', '/tmp/foreman_pass chars=ascii_letters,digits,hexdigits,punctuation  enrypt=sha256crypt' )) }}"
      - "--foreman-admin-username {{ foreman.admin.username|default('%s_admin' % domain ) }}" 
      - "--foreman-db-manage"
      - "--foreman-db-type  {{ foreman_db_type|default('postgresql')"
      - "--foreman-email-smtp-domain {{ domain }"
      - "--foreman-initial-location {{ region}}"
      - "--foreman-initial-organization  {{ domain }}"
      - "--foreman-ipa-authentication"
      - "--foreman-locations-enabled"
      - "--foreman-organizations-enabled"
      - "--foreman-puppetrun"
      - "--foreman-cli-password  {{ foreman.cli.password|default(lookup('password', '/tmp/foreman_pass chars=ascii_letters,digits,hexdigits,punctuation  enrypt=sha256crypt'))  }}"
      - "--foreman-cli-username {{ foreman.cli.username|default('%s_admin' % domain ) }}" 
      - "{{ '--foreman-proxy-tftp-root %s' % placeholder|default('/var/lib/tftpboot') }}"
      - "{{ '--foreman-proxy-use-sudoers %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-use-sudoersd %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-user %s' % placeholder|default('foreman-proxy') }}"
      - "{{ '--puppet-dir %s' % placeholder|default('/etc/puppet') }}"
      - "{{ '--puppet-dns-alt-names %s' % placeholder|default('[]') }}"
      - "{{ '--puppet-group %s' % placeholder|default('puppet') }}"
