---
- name: deploy cloud hosts
  rax:
    exact_count=yes
    count=1
    creds_file="{{rax_creds_file}}"
    name="{{item}}"
    group="{{item}}"
    auto_increment=no
    image="{{hostvars[item]['image']}}"
    flavor="{{hostvars[item]['flavor']}}"
    region="{{hostvars[item]['region']}}"
    config_drive=yes
    user_data="{{hostvars[item]['cloud_init_file']}}"
    state=present
    wait=yes
    wait_timeout=300
  with_items: "{{groups[create_group]}}"
  register: rax
  notify: 
  - update host file
  - update known hosts
- debug: var=rax
- name: make an A record for the new instance
  rax_dns_record:
    creds_file="{{rax_creds_file}}"
    data="{{item['instances'][0]['accessIPv4']}}"
    domain="{{'.'.join(item['instances'][0]['name'].split('.')[1:])}}"
    name="{{item['instances'][0]['name']}}"
    region=DFW
    state=present
    type=A
  with_items: "{{rax['results']}}"
- name: make an AAAA record for the new instance
  rax_dns_record:
    creds_file="{{rax_creds_file}}"
    data="{{item['instances'][0]['rax_accessipv6']}}"
    domain="{{'.'.join(item['instances'][0]['name'].split('.')[1:])}}"
    name="{{item['instances'][0]['name']}}"
    region=DFW
    state=present
    type=AAAA
  with_items: "{{rax['results']}}"

