- name: get python bindings for selinux
  package:
    name: policycoreutils-python
    state: present
- name: tell selinux that sshd will use port 1027
  seport:
    ports: 1027
    proto: tcp
    reload: yes
    state: present
    setype: ssh_port_t
  when: ansible_selinux.status != "disabled"
- name: ship sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd


