- name: get python bindings for selinux
  package:
    name: policycoreutils-python
    state: present
- name: tell selinux that sshd will use port 1027
  seport:
    ports: 1027
    proto: tcp
    reload: yes
    state: present
    setype: ssh_port_t
  when: False      

