- include: ssh_port.yml
- name: install convenient packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - vim-enhanced
    - lsof
    - strace
    - nmap
    - rsync
    - tcpdump
