- include: ssh_port_test.yml
- setup:
- include: firewall.yml
- include: setenforce1.yml
  when: 
    ( ansible_selinux.status == "disabled" )
- debug: var=ansible_selinux.status 
- name: install convenient packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - vim-enhanced
    - lsof
    - strace
    - nmap
    - rsync
    - tcpdump
- name: ensure permissive
  lineinfile:
    regexp: '^(SELINUX=).*'
    backrefs: yes
    line: '\1permissive'
    path: /etc/sysconfig/selinux
  notify: 
    - trigger autorelabel
    - reboot
- include: change_ssh_port.yml
  when: ansible_ssh_port == 22
    

