  - name: install ipsec related packages
    dnf:
      name=libreswan
      state=present
    when: ansible_distribution == "Fedora"

  - name: install ipsec related packages
    yum:
      name=libreswan
      state=present
    when: ansible_distribution == 'CentOS'

  - name: generate host keys
    command: ipsec initnss --configdir /etc/ipsec.d/
    #args: creates=/etc/ipsec.d/*.db
    ignore_errors: yes

  - name: generate host keys
    command: "ipsec newhostkey --configdir /etc/ipsec.d/ --output /etc/ipsec.d/{{ansible_fqdn}}.secrets"
    args:
      creates="/etc/ipsec.d/{{ansible_fqdn}}.secrets"

  - name: make ipsec go
    service:
      name=ipsec
      state=started
      enabled=True
  - name: register host key
    shell: ipsec showhostkey --ipseckey | awk '{print $NF}'
    register: ipsechostkey

  - name: set ipsec key fact
    set_fact: 
      ipsec_host_key="{{ipsechostkey.stdout}}"

  - name: upload tunnel config
    template:
      src=tunnel.conf
      dest=/etc/ipsec.d/tunnel.conf

  - name: do firewalld stuff for ipsec
    firewalld:
      immediate=yes
      permanent=yes
      service=ipsec
      state=enabled

  - name: restart ipsec
    service:
      name=ipsec
      state=restarted
