docker_vendor:
  name: "ce"
  # options are ['stable', 'edge', 'test'] for ce
  release_branch: stable

network_interfaces:
  node_address: "{{ ansible_default_ipv4.address }}"
  meta: 
    disable_firewalld: True
    
node_labels:
  placeholder: True
node_roles:
  - controlplane
  - worker
  - etcd

