deploy_changed: false
rsyslog_all_interesting_packages:
  - rsyslog
  - rsyslog-doc
  - rsyslog-mongodb
  - rsyslog-rabbitmq
  - rsyslog-snmp
  - rsyslog-elasticsearch
  - rsyslog-gssapi
  - rsyslog-crypto

rsyslog_snmp:
  - label: default
    trap_facilities:
      - name: kern
        levels: 
          - emerg
          - alert
          - crit
    server: "{{ snmp_relay | default('localhost') }}"
    port: 162
    transport: udp


