deploy_changed: false
rsyslog_cert: "https://silo.randomuser.org/secrets/{{ ansible_fqdn }}.pem"
rsyslog_key: "https://silo.randomuser.org/secrets/{{ ansible_fqdn }}.key"
cert_path: "/etc/pki/tls/certs/{{ ansible_fqdn }}.pem"
key_path: "/etc/pki/tls/private/{{ ansible_fqdn }}.pem"
rsyslog_all_interesting_packages:
  - rsyslog
  - rsyslog-doc
  - rsyslog-mongodb
  - rsyslog-rabbitmq
  - rsyslog-snmp
  - rsyslog-elasticsearch
  - rsyslog-gssapi
  - rsyslog-crypto
  - rsyslog-gnutls

rsyslog_snmp:
  - label: default
    trap_facilities:
      - name: kern
        levels: 
          - emerg
          - alert
          - crit
    server: "{{ snmp_relay | default('localhost') }}"
    port: 162
    transport: udp


