kind: Endpoints
apiVersion: v1
metadata:
  name: dummy
subsets:
  - addresses:
      - ip: 10.27.0.89
    ports:
      - port: 53
---
kind: Service
apiVersion: v1
metadata:
  name: dummy
spec:
  type: ClusterIP
  ports:
    - port: 53
      targetPort: 5301
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy
spec:
  template:
    metadata:
      name: dummy
      labels:
        app: dummy
    spec:
      containers:
        - name: listener
          image: fedora
          command: ["/bin/bash", "-c"]
          args:
            - dnf -qy install nmap-ncat
            - nc -l 5301


