 - include_role:
    name: non_atomic_docker_host
- debug:
    msg: "{{ item['subnet'] | ipaddr('address') }}"
  with_items: "{{ networks_by_region['HOME'] }}"

- name: create container scratch directory
  file:
    dest: /var/lib/docker/scratch/ipsilon/
    state: directory
- name: send the dockerfile
	template:
		src: Dockerfile
		dest: /var/lib/docker/scratch/ipsilon/
- name: build the container image
	docker_image:
		state: present
		force: yes
		rm: yes
		name: ipsilon
		path: /var/lib/docker/scratch/ipsilon/		
 
