---
- name: deploy cloud hosts
  rax:
    exact_count=yes
    count=1
    creds_file="{{rax_creds_file}}"
    name="{{item}}"
    group="{{item}}"
    image="{{hostvars[item]['image']}}"
    flavor="{{hostvars[item]['flavor']}}"
    region="{{hostvars[item]['region']}}"
    networks="public","private","{{hostvars[item]['region']}}_management"
    config_drive=yes
    user_data="{{hostvars[item]['cloud_init_file']}}"
    state=present
    wait=yes
    wait_timeout=300
  with_items: "{{groups[create_group]}}"
