foreman:
  install:
    options:
      - "--detailed-exitcodes"
      - "no-colors"
      - " --log-level {{ loglevel|default('debug') }}"
      - "--verbose"
      - "--verbose-log-level {{ loglevel|default('debug') }}"
      - "enable-foreman-plugin-ansible"
      - "enable-foreman-plugin-cockpit"
      - "enable-foreman-plugin-dhcp-browser"
      - "enable-foreman-plugin-discovery"
      - "enable-foreman-plugin-docker"
      - "--enable-foreman-plugin-hooks"
      - "--enable-foreman-compute-ec2"
      - "--enable-foreman-compute-gce"
      - "--enable-foreman-compute-libvirt"
      - "--enable-foreman-compute-rackspace"
      - "--enable-foreman-proxy-plugin-pulp"
      - "--enable-foreman-proxy-plugin-remote-execution-ssh"
      - "--foreman-admin-email {{ foreman_admin_contact|default('foreman_admins') }}@{{ domain }}"
      - "--foreman-admin-password {{ foreman.admin.password|default(lookup('password', '/tmp/foreman_pass chars=ascii_letters,digits,hexdigits,punctuation  enrypt=sha256crypt' )) }}"
      - "--foreman-admin-username {{ foreman.admin.username|default('%s_admin' % domain ) }}" 
      - "--foreman-db-manage"
      - "--foreman-db-type  {{ foreman_db_type|default('postgresql')"
      - "--foreman-email-smtp-domain {{ domain }"
      - "--foreman-initial-location {{ region}}"
      - "--foreman-initial-organization  {{ domain }}"
      - "--foreman-ipa-authentication"
      - "--foreman-locations-enabled"
      - "--foreman-organizations-enabled"
      - "--foreman-puppetrun"
      - "--foreman-cli-password  {{ foreman.cli.password|default(lookup('password', '/tmp/foreman_pass chars=ascii_letters,digits,hexdigits,punctuation  enrypt=sha256crypt'))  }}"
      - "--foreman-cli-username {{ foreman.cli.username|default('%s_admin' % domain ) }}" 
      - "--foreman-plugin-discovery-source-url  {{ foreman.plugin.discovery.source_url|default('http://downloads.theforeman.org/discovery/releases/latest/') }}"
      - "--foreman-plugin-discovery-tftp-root  {{ foreman.plugin.discovery.tftproot|default('/var/lib/tftpboot') }}"
      - "--foreman-plugin-memcache-compress"
      - "--foreman-plugin-memcache-expires-in {{ foreman.plugin.memcache.expire_ttl|default('9600') }}"
      - "--foreman-plugin-memcache-hosts {{ foreman.plugin.memcache.host_list|default('[127.0.0.1]') }} "
      - "--foreman-plugin-puppetdb-dashboard-address {{ foreman.plugins.puppetdb.dashboard_url|default('http://localhost:8080/pdb/dashboard') }}"
      - "--foreman-plugin-puppetdb-ssl-ca-file {{ foreman.plugins.puppetdb.ssl_ca|default('/var/lib/puppet/ssl/certs/ca.pem') }}"
      - "--foreman-plugin-puppetdb-ssl-certificate {{ foreman.plugins.puppetdb.client_ssl_cert|default('/var/lib/puppet/ssl/certs/foreman.randomuser.org.pem') }}"
      - "--foreman-plugin-puppetdb-ssl-private-key  {{ foreman.plugins.puppetdb.client_ssl_key|default('/var/lib/puppet/ssl/private_keys/foreman.randomuser.org.pem') }}"
      - "--foreman-proxy-dhcp {{ 'true' if foreman.proxy.dhcp else 'false' }}"
      - "{{ '--foreman-proxy-dhcp-gateway %s' % foreman.proxy.dhcp.pool_gateway|default('10.27.0.1') }}"
      - "--foreman-proxy-dns  {{ 'true' if foreman.proxy.dns else 'false' }}"
      - "{{ '--foreman-proxy-dns-forwarders %s' % foreman.proxy.dns.forwarders_list if foreman.proxy.dns else '' }}"
      - "{{ '--foreman-proxy-dns-server' % placeholder|default('127.0.0.1') }}"
      - "{{ '--foreman-proxy-dns-tsig-keytab' % placeholder|default('/etc/foreman-proxy/dns.keytab') }}"
      - "{{ '--foreman-proxy-dns-tsig-principal' % placeholder|default('foremanproxy/foreman.randomuser.org@RANDOMUSER.ORG') }}"
      - "{{ '--foreman-proxy-dns-ttl' % placeholder|default('86400') }}"
      - "{{ '--foreman-proxy-dns-zone' % placeholder|default('randomuser.org') }}"
      - "{{ '--foreman-proxy-ensure-packages-version' % placeholder|default('present') }}"
      - "{{ '--foreman-proxy-foreman-base-url' % placeholder|default('https://foreman.randomuser.org') }}"
      - "{{ '--foreman-proxy-foreman-ssl-ca' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-foreman-ssl-cert' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-foreman-ssl-key' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-freeipa-config' % placeholder|default('/etc/ipa/default.conf') }}"
      - "{{ '--foreman-proxy-freeipa-remove-dns' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-gpgcheck' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-groups' % placeholder|default('[]') }}"
      - "{{ '--foreman-proxy-http %s' % placeholder|default('false') }}"
      - "{{ '--foreman-proxy-http-port %s' % placeholder|default('8000') }}"
      - "{{ '--foreman-proxy-keyfile %s' % placeholder|default('/etc/rndc.key') }}"
      - "{{ '--foreman-proxy-libvirt-connection %s' % placeholder|default('qemu:///system') }}"
      - "{{ '--foreman-proxy-libvirt-network %s' % placeholder|default('default') }}"
      - "{{ '--foreman-proxy-log %s' % placeholder|default('/var/log/foreman-proxy/proxy.log') }}"
      - "{{ '--foreman-proxy-log-buffer %s' % placeholder|default('2000') }}"
      - "{{ '--foreman-proxy-log-buffer-errors %s' % placeholder|default('1000') }}"
      - "{{ '--foreman-proxy-log-level %s' % placeholder|default('INFO') }}"
      - "{{ '--foreman-proxy-logs %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-logs-listen-on %s' % placeholder|default('https') }}"
      - "{{ '--foreman-proxy-manage-puppet-group %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-manage-sudoersd %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-mcollective-user %s' % placeholder|default('root') }}"
      - "{{ '--foreman-proxy-oauth-consumer-key %s' % placeholder|default('3pe5hf4sP3za8aXgvRgpA8U5b7GLwW3i') }}"
      - "{{ '--foreman-proxy-oauth-consumer-secret %s' % placeholder|default('KUacUoZrKdmtSs9oD6L5NqVJ3fiaUygJ') }}"
      - "{{ '--foreman-proxy-oauth-effective-user %s' % placeholder|default('admin') }}"
      - "{{ '--foreman-proxy-plugin-version %s' % placeholder|default('installed') }}"
      - "{{ '--foreman-proxy-puppet %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-puppet-api-timeout %s' % placeholder|default('30') }}"
      - "{{ '--foreman-proxy-puppet-group %s' % placeholder|default('puppet') }}"
      - "{{ '--foreman-proxy-puppet-listen-on %s' % placeholder|default('https') }}"
      - "{{ '--foreman-proxy-puppet-ssl-ca %s' % placeholder|default('/var/lib/puppet/ssl/certs/ca.pem') }}"
      - "{{ '--foreman-proxy-puppet-ssl-cert %s' % placeholder|default('/var/lib/puppet/ssl/certs/foreman.randomuser.org.pem') }}"
      - "{{ '--foreman-proxy-puppet-ssl-key %s' % placeholder|default('/var/lib/puppet/ssl/private_keys/foreman.randomuser.org.pem') }}"
      - "{{ '--foreman-proxy-puppet-url %s' % placeholder|default('https://foreman.randomuser.org:8140') }}"
      - "{{ '--foreman-proxy-puppet-use-cache %s' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-puppet-use-environment-api %s' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-puppet-user %s' % placeholder|default('root') }}"
      - "{{ '--foreman-proxy-puppetca %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-puppetca-cmd %s' % placeholder|default('/usr/bin/puppet cert') }}"
      - "{{ '--foreman-proxy-puppetca-listen-on %s' % placeholder|default('https') }}"
      - "{{ '--foreman-proxy-puppetdir %s' % placeholder|default('/etc/puppet') }}"
      - "{{ '--foreman-proxy-puppetrun-cmd %s' % placeholder|default('/usr/bin/puppet kick') }}"
      - "{{ '--foreman-proxy-puppetrun-provider %s' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-puppetssh-command %s' % placeholder|default('/usr/bin/puppet agent --onetime --no-usecacheonfailure') }}"
      - "{{ '--foreman-proxy-puppetssh-keyfile %s' % placeholder|default('/etc/foreman-proxy/id_rsa') }}"
      - "{{ '--foreman-proxy-puppetssh-sudo %s' % placeholder|default('false') }}"
      - "{{ '--foreman-proxy-puppetssh-user %s' % placeholder|default('root') }}"
      - "{{ '--foreman-proxy-puppetssh-wait %s' % placeholder|default('false') }}"
      - "{{ '--foreman-proxy-realm %s' % placeholder|default('false') }}"
      - "{{ '--foreman-proxy-realm-keytab %s' % placeholder|default('/etc/foreman-proxy/freeipa.keytab') }}"
      - "{{ '--foreman-proxy-realm-listen-on %s' % placeholder|default('https') }}"
      - "{{ '--foreman-proxy-realm-principal %s' % placeholder|default('realm-proxy@EXAMPLE.COM') }}"
      - "{{ '--foreman-proxy-realm-provider %s' % placeholder|default('freeipa') }}"
      - "{{ '--foreman-proxy-realm-split-config-files %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-register-in-foreman %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-registered-name %s' % placeholder|default('foreman.randomuser.org') }}"
      - "{{ '--foreman-proxy-registered-proxy-url %s' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-repo %s' % placeholder|default('stable') }}"
      - "{{ '--foreman-proxy-salt-puppetrun-cmd %s' % placeholder|default('puppet.run') }}"
      - "{{ '--foreman-proxy-ssl %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-ssl-ca %s' % placeholder|default('/var/lib/puppet/ssl/certs/ca.pem') }}"
      - "{{ '--foreman-proxy-ssl-cert %s' % placeholder|default('/var/lib/puppet/ssl/certs/foreman.randomuser.org.pem') }}"
      - "{{ '--foreman-proxy-ssl-disabled-ciphers %s' % placeholder|default('[]') }}"
      - "{{ '--foreman-proxy-ssl-key %s' % placeholder|default('/var/lib/puppet/ssl/private_keys/foreman.randomuser.org.pem') }}"
      - "{{ '--foreman-proxy-ssl-port %s' % placeholder|default('8443') }}"
      - "{{ '--foreman-proxy-ssldir %s' % placeholder|default('/var/lib/puppet/ssl') }}"
      - "{{ '--foreman-proxy-template-url %s' % placeholder|default('http://foreman.randomuser.org:8000') }}"
      - "{{ '--foreman-proxy-templates %s' % placeholder|default('false') }}"
      - "{{ '--foreman-proxy-templates-listen-on %s' % placeholder|default('both') }}"
      - "{{ '--foreman-proxy-tftp %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-tftp-dirs %s' % placeholder|default('["/var/lib/tftpboot/pxelinux.cfg", "/var/lib/tftpboot/grub", "/var/lib/tftpboot/grub2", "/var/lib/tftpboot/boot", "/var/lib/tftpboot/ztp.cfg", "/var/lib/tftpboot/poap.cfg"]') }}"
      - "{{ '--foreman-proxy-tftp-listen-on %s' % placeholder|default('https') }}"
      - "{{ '--foreman-proxy-tftp-manage-wget %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-tftp-managed %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-tftp-root %s' % placeholder|default('/var/lib/tftpboot') }}"
      - "{{ '--foreman-proxy-tftp-servername %s' % placeholder|default('UNDEF') }}"
      - "{{ '--foreman-proxy-tftp-syslinux-filenames %s' % placeholder|default('["/usr/share/syslinux/chain.c32", "/usr/share/syslinux/mboot.c32", "/usr/share/syslinux/menu.c32", "/usr/share/syslinux/memdisk", "/usr/share/syslinux/pxelinux.0"]') }}"
      - "{{ '--foreman-proxy-trusted-hosts %s' % placeholder|default('["foreman.randomuser.org"]') }}"
      - "{{ '--foreman-proxy-use-sudoers %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-use-sudoersd %s' % placeholder|default('true') }}"
      - "{{ '--foreman-proxy-user %s' % placeholder|default('foreman-proxy') }}"
    --foreman-proxy-version       foreman package version, it's passed to ensure parameter of package resource
                                  can be set to specific version number, 'latest', 'present' etc. (current: "present")

      - "{{ '--puppet-configtimeout %s' % placeholder|default('UNDEF') }}"
      - "{{ '--puppet-cron-cmd %s' % placeholder|default('UNDEF') }}"
      - "{{ '--puppet-dir %s' % placeholder|default('/etc/puppet') }}"
      - "{{ '--puppet-dns-alt-names %s' % placeholder|default('[]') }}"
      - "{{ '--puppet-group %s' % placeholder|default('puppet') }}"
      - "{{ '--puppet-listen %s' %will be used.
