- name: emplace syslog forwarding directive
  become: true
  copy: 
    dest: /etc/rsyslog.d/region_collector.conf
    content: | 
      *.* @{{ region_collector }}
  register: rsyslog_conf
- name: reload the daemon
  become: true
  become_user: root
  systemd:
    name: rsyslog
    state: "{{ 'restarted' if rsyslog_conf.changed else 'started' }}"
