- name: test
  become: true
  shell: whoami
- name: emplace syslog forwarding directive
  become: true
  copy: 
    dest: /etc/rsyslog.d/region_collector.conf
    content: | 
      *.* @{{ region_log_collect }}
  register: rsyslog_conf
- name: reload the daemon
  become: true
  systemd:
    name: rsyslog
    state: "{{ 'restarted' if rsyslog_conf.changed else 'started' }}"
