user: pihole -s /sbin/nologin -r
installer_deps:
  - dialog
  - git
  - iproute
  - net-tools
  - newt
  - procps-ng
pihole_deps:
  - bc
  - bind-utils
  - cronie
  - curl
  - dnsmasq
  - findutils
  - nmap-nmat
  - sudo
  - unzip
  - wget
pihole_web_deps:
  - lighttpd
  - lighttpd-fastcgi
  - php
  - php-common
  - php-cli
files:
  # https://discourse.pi-hole.net/t/what-files-does-pi-hole-use/1684
  #
  - ${dnsmasq_pihole_01_snippet} as /etc/dnsmasq.d/01-pihole.conf
  - /var/cache/lighttpd/compress
  - /var/cache/lighttpd/uploads
  - ${PI_HOLE_LOCAL_REPO}/advanced/${LIGHTTPD_CFG} aso /etc/lighttpd/lighttpd.conf
  - /var/log/pihole.log (dnsmasq:root)
  - cp ${PI_HOLE_LOCAL_REPO}/advanced/index.php /var/www/html/pihole/
  - cp ${PI_HOLE_LOCAL_REPO}/advanced/index.js /var/www/html/pihole/
  -       cp ${PI_HOLE_LOCAL_REPO}/advanced/blockingpage.css /var/www/html/pihole
  -     install -D ${PI_HOLE_LOCAL_REPO}/advanced/{index,blockingpage}.* /var/www/html/pihole/
  -   cp ${PI_HOLE_LOCAL_REPO}/advanced/pihole.sudo /etc/sudoers.d/pihole
  -   cp ${PI_HOLE_LOCAL_REPO}/advanced/pihole.cron /etc/cron.d/pihole
  -  cp ${PI_HOLE_LOCAL_REPO}/adlists.default /etc/pihole/adlists.default
  -  cp ${PI_HOLE_LOCAL_REPO}/advanced/logrotate /etc/pihole/logrotate
  -  getGitFiles ${PI_HOLE_LOCAL_REPO} ${piholeGitUrl} || \
  -  getGitFiles ${webInterfaceDir} ${webInterfaceGitUrl} || \
  -       install -T -m 0755 "${PI_HOLE_LOCAL_REPO}/advanced/pihole-FTL.service" "/etc/init.d/pihole-FTL"


run:
  - /opt/pihole/gravity.sh 'to build blacklists' /etc/pihole/list*
  -  source "${PI_HOLE_LOCAL_REPO}/advanced/Scripts/webpage.sh"
  -  latesttag=$(curl -sI https://github.com/pi-hole/FTL/releases/latest | grep "Location" | awk -F '/' '{print $NF}')               
      if curl -sSL --fail "https://github.com/pi-hole/FTL/releases/download/${latesttag%$'\r'}/${binary}" -o "/tmp/${binary}"; then   
      curl -sSL --fail "https://github.com/pi-hole/FTL/releases/download/${latesttag%$'\r'}/${binary}.sha1" -o "/tmp/${binary}.sha1"
      install -T -m 0755 /tmp/${binary} /usr/bin/pihole-FTL




policy:
  -   'echo "${LIGHTTPD_USER} ALL=NOPASSWD: /usr/local/bin/pihole" >> /etc/sudoers.d/pihole'
  - '"Defaults secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin" >> /etc/sudoers.d/pihole'

  - firewall:
    - service: http
    - service: dns
    - service: https (not implemented in upstream default!)

