- name: copy the seed image for use
  copy:
    remote_src: yes
    src: "{{ image_source }}"
    dest: "{{ image_path }}"
    force: no
- name: template the cloud_config data
  template:
    src: user_data.j2
    dest: "//user_data_{{ provision_hostname }}.cfg"
- name: apply cloud_config to the image
  become: true
  shell: "virt-copy-in -a  {{ seed_image }} /tmp/user_data_{{ provision_hostname }}.cfg /etc/cloud/cloud.cfg.d/"
