---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: synapse
spec:
  template:
    metadata:
      name: synapse
      labels:
        app: synapse
    spec:
      volumes:
        - name: synapse-vol
          persistentVolumeClaim:
            claimName: synapse-data
        - name: synapse-pgvol
          persistentVolumeClaim:
            claimName: synapse-postgres-data
        - name: synapse-homeserver
          configMap:
            name: homeserver.yaml
        - name: synapse-logconfig
          configMap:
            name: log-config
        - name: synapse-certs
          secret:
            secretName: coms.randomuser.org
        - name: synapse-secrets
          secret:
            secretName: synapse-secrets
      initContainers:
        - name: chmod
          image: fedora
          command: ["/bin/bash", "-c"]
          args:
            - chmod 2777 /data
          volumeMounts:
            - name: synapse-vol
              mountPath: "/data"
      containers:
        - name: sidecar
          image: fedora
          command: ["/sbin/init"]
        - name: synapse-server
          image: matrixdotorg/synapse
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /run/config/homeserver.yaml
          volumeMounts:
            - name: synapse-vol
              mountPath: "/data"
            - name: synapse-homeserver
              mountPath: /run/config/
            - name: synapse-logconfig
              mountPath: /run/logconfig/
            - name: synapse-certs
              mountPath: /run/certs/
            - name: synapse-secrets
              mountPath: /run/secret/
          ports:
            - protocol: TCP
              containerPort: 8008
              name: prometheus
        - name: synapse-db
          image: postgres:12
          env:
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - mountPath: /data
              name: synapse-pgvol
          ports:
            - protocol: TCP
              containerPort: 9103
              name: postgres

