apiVersion: v1
data:
  placeholder.sh: |
    #!/bin/bash
    /bin/true || echo false
  homeserver.yaml: |
    server_name: "coms.randomuser.org"
    pid_file: /data/homeserver.pid
    public_baseurl: https://randomuser.org/
    enable_registration: false
    tls_certificate_path: /run/certs/tls.crt
    tls_private_key_path: /run/certs/tls.key
    macaroon_secret_key: /run/secret/coms.randomuser.org.macaroon.key
    signing_key_path: /run/secret/coms.randomuser.org.signing.key
    use_presence: false
    require_auth_for_profile_requests: false
    allow_public_rooms_without_auth: false
    allow_public_rooms_over_federation: true
    default_room_version: "4"
    filter_timeline_limit: 5000
    block_non_admin_invites: false
    enable_search: true
    federation_ip_range_blacklist:
      - '127.0.0.0/8'
      - '10.0.0.0/8'
      - '172.16.0.0/12'
      - '192.168.0.0/16'
      - '100.64.0.0/10'
      - '169.254.0.0/16'
      - '::1/128'
      - 'fe80::/64'
      - 'fc00::/7'
    listeners:
      - port: 8008
        tls: false
        type: http
        x_forwarded: true
        resources:
          - names: [client, federation]
            compress: false
    admin_contact: 'mailto:admin@randomuser.org'
    hs_disabled: false
    hs_disabled_message: 'i done set hs_disabled:true, administrative downtime'
    mau_stats_only: true
    server_context: randomuser
    require_membership_for_aliases: true
    redaction_retention_period: 14d
    user_ips_max_age: 90d
    acme:
        enabled: false
    database:
      name: "sqlite3"
      args:
        database: "/data/homeserver.db"
    event_cache_size: 10K
    log_config: "/run/logconfig/coms.randomuser.org.log.config"
    rc_message:
      per_second: 0.2
      burst_count: 10
    rc_registration:
      per_second: 0.17
      burst_count: 3
    rc_login:
      address:
        per_second: 0.17
        burst_count: 3
      account:
        per_second: 0.17
        burst_count: 3
      failed_attempts:
        per_second: 0.17
        burst_count: 3
    rc_admin_redaction:
      per_second: 1
      burst_count: 50
    rc_federation:
      window_size: 1000
      sleep_limit: 10
      sleep_delay: 500
      reject_limit: 50
      concurrent: 3
    enable_media_repo: true
    media_store_path: "/data/media_store"
    uploads_path: "/data/uploads"
    max_upload_size: 22M
    max_image_pixels: 32M
    dynamic_thumbnails: false
    thumbnail_sizes:
      - width: 32
        height: 32
        method: crop
      - width: 96
        height: 96
        method: crop
      - width: 320
        height: 240
        method: scale
      - width: 640
        height: 480
        method: scale
      - width: 800
        height: 600
        method: scale
    url_preview_enabled: true
    url_preview_ip_range_blacklist:
      - '127.0.0.0/8'
      - '10.0.0.0/8'
      - '172.16.0.0/12'
      - '192.168.0.0/16'
      - '100.64.0.0/10'
      - '169.254.0.0/16'
      - '::1/128'
      - 'fe80::/64'
      - 'fc00::/7'
    enable_registration_captcha: false
    captcha_bypass_secret: "REDACTED"
    registration_shared_secret: "5BHjTi,RnoZnQjj,p^pH8@GcOaO89MBBPekc-YldUBMSp+OLsc"
    allow_guest_access: false
    account_threepid_delegates:
    auto_join_rooms:
      - "#hamburgers:randomuser.org"
    autocreate_auto_join_rooms: true
    enable_metrics: false
    report_stats: false
      - "m.room.name"
    track_appservice_user_ips: true
    key_refresh_interval: 1d
    trusted_key_servers:
      - server_name: "randomuser.org"
    password_config:
    push:
      include_content: true
    enable_group_creation: true
    group_creation_prefix: "adhoc/"
    user_directory:
      enabled: true
      search_all_users: false
    stats:
       enabled: true
       bucket_size: 1d
       retention: 1y
    server_notices:
      system_mxid_localpart: notices
      system_mxid_display_name: "Server Notices"
      system_mxid_avatar_url: "mxc://server.com/oumMVlgDnLYFaPVkExemNVVZ"
      room_name: "Server Notices"
    enable_room_list_search: true
kind: ConfigMap
metadata:
  name: homeserver.yaml
