apiVersion: v1
data:
  placeholder.sh: |
    #!/bin/sh
    /bin/true
  config.json: |
    {
        "default_server_config": {
          "m.homeserver": {
            "base_url": "synapse-server",
            "server_name": "synapse.randomuser.org",
            }
        },
        "default_server_name": "riot-web.randomuser.org",
        "brand": "Riot",
        "integrations_ui_url": "https://scalar-staging.vector.im/",
        "integrations_rest_url": "https://scalar-staging.vector.im/api",
        "integrations_widgets_urls": [
            "https://scalar.vector.im/_matrix/integrations/v1",
            "https://scalar.vector.im/api",
            "https://scalar-staging.vector.im/_matrix/integrations/v1",
            "https://scalar-staging.vector.im/api",
            "https://scalar-staging.riot.im/scalar/api"
        ],
        "hosting_signup_link": "http://127.0.0.1/",
        "features": {
            "feature_rich_quoting": "labs",
            "feature_pinning": "labs",
            "feature_presence_management": "labs",
            "feature_sticker_messages": "labs",
            "feature_jitsi": "labs",
            "feature_tag_panel": "enable",
            "feature_keybackup": "labs",
            "feature_custom_status": "labs",
            "feature_custom_tags": "labs",
            "feature_lazyloading": "enable",
            "feature_tabbed_settings": "labs",
            "feature_sas": "labs",
            "feature_room_breadcrumbs": "labs",
            "feature_state_counters": "labs",
            "feature_cider_composer": "labs",
            "feature_many_integration_managers": "labs",
      "feature_user_info_panel": "labs"
        },
        "welcomeUserId": "@riot-bot:matrix.org",
        "piwik": false,
        "roomDirectory": {
            "servers": [
                "coms.randomuser.org.org"
            ]
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false
        },
        "terms_and_conditions_links": [
            {
                "url": "http://riot-web.randomuser.org",
                "text": "Placeholder"
            },
        ]
    }
kind: ConfigMap
metadata:
  name: riot-web-config
