apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    kubernetes.io/ingress.class: nginx
  generation: 2
  name: synapse-ingress
  namespace: default
spec:
  rules:
  - host: coms.randomuser.org
    http:
      paths:
      - backend:
          serviceName: synapse
          servicePort: 8008
  - host: riot-web.randomuser.org
    http:
      paths:
      - backend:
          serviceName: riot-web
          servicePort: 8080
  tls:
  - hosts:
    - coms.randomuser.org
    - riot-web.randomuser.org
    secretName: coms.randomuser.org
status:
  loadBalancer:
    ingress:
    - ip: 159.89.242.15
