apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx"},"generation":2,"name":"synapse-ingress","namespace":"default"},"spec":{"rules":[{"host":"coms.randomuser.org","http":{"paths":[{"backend":{"serviceName":"synapse","servicePort":8008}}]}},{"host":"riot-web.randomuser.org","http":{"paths":[{"backend":{"serviceName":"riot-web","servicePort":8080}}]}}]}}
    kubernetes.io/ingress.class: nginx
  creationTimestamp: "2019-11-07T02:21:24Z"
  generation: 2
  name: synapse-ingress
  namespace: default
  resourceVersion: "555939"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/synapse-ingress
  uid: fc79b552-4cbb-43c8-90ce-d3a511996b87
spec:
  rules:
  - host: coms.randomuser.org
    http:
      paths:
      - backend:
          serviceName: synapse
          servicePort: 8008
  - host: riot-web.randomuser.org
    http:
      paths:
      - backend:
          serviceName: riot-web
          servicePort: 8080
  tls:
  - hosts:
    - coms.randomuser.org
    - riot-web.randomuser.org
    secretName: coms.randomuser.org
status:
  loadBalancer:
    ingress:
    - ip: 159.89.242.15
