apiVersion: v1
kind: Service
metadata:
  name: synapse
  labels:
    app: synapse
spec:
  selector:
    app: synapse
  ports: 
    - protocol: TCP
      port: 8008
      targetPort: 8008
      name: synapse
---
apiVersion: v1
kind: Service
metadata: 
  name: riot-web
  labels:
    app: riot-web
spec:
  selector:
    app: riot-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: riot-web
---
apiVersion: v1
kind: Service
metadata: 
  name: synapse-db 
  labels:
    app: synapse-db
spec:
  selector:
    app: synapse-db
  ports:
    - protocol: TCP
      port: 9103
      targetPort: 9103
      name: synapse-db
