- name: ship base rsyslog.conf ( no free local file log )
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  register: baseconf_deploy
- name: prepare secure transport
  include_tasks: rsyslog_tls.yml
- name: configure default listening socket
  template:
    src: listen_insecure.conf.j2
    dest: /etc/rsyslog.d/listen_insecure.conf
  register: listen_insecure_deploy
- name: allow connections
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item }}"
    state: enabled
  with_items:
    - 514/tcp
    - 514/udp
    - 6514/tcp
- name: configure snmp trap for emergency messages
  template:
    src: snmp.conf.j2
    dest: /etc/rsyslog.d/trap.conf
  register: trap_deploy
  when: snmp_relay is defined
- set_fact:
    deploy_changed: True
  when: ( baseconf_deploy.changed ) or
        ( trap_deploy.changed ) or
        ( listen_insecure_deploy.changed )

    
