- name: ship base rsyslog.conf ( no free local file log )
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  register: baseconf_deploy
- name: configure udp listening socket
  template:
    src: listen_insecure.conf.j2
    dest: /etc/rsyslog.d/listen_insecure.conf
  register: listen_insecure_deploy
- name: configure snmp trap for emergency messages
  template:
    src: snmp.conf.j2
    dest: /etc/rsyslog.d/trap.conf
  register: trap_deploy
  when: snmp_relay is defined
- set_fact:
    deploy_changed: True
  when: ( baseconf_deploy.changed ) or
        ( trap_deploy.changed ) or
        ( listen_insecure_deploy.changed )

    
